version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  app:
    build: .
    container_name: express-app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '3000:3000'
    depends_on:
      - redis
    volumes:
      - .:/app

volumes:
  redis-data:
